import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSideBar from "@/components/app-sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "XeeAI",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      <div>
        <SidebarProvider>
        <AppSideBar />
          <div>
            <SidebarTrigger />
          </div>
        </SidebarProvider>
      </div>
      <main className="flex-1">
        {children}
      </main>
    </div>
  );
}