import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { SidebarComponent, History } from "@/components/sidebar";

export const metadata: Metadata = {
  title: "XeeAI",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <SidebarComponent />
      <History />
      {children}
    </main>
  );
}
