import { SidebarComponent } from "@/components/SideBar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "XeeAI",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-row min-h-screen">
      <div className="flex-shrink-0">
        <SidebarProvider>
          <SidebarComponent />
          <SidebarTrigger />
        </SidebarProvider>
      </div>
      <main className="flex-1 flex items-center justify-center">
        {children}
      </main>
    </div>
  );
}
